# --- Genesis constants (tweak as you like) ---
GENESIS_EPOCH_ISO = "2125-01-01T00:00:00Z"   # time-lock horizon

GENESIS_WALLET_ID   = "WALLET-GENESIS-0001"
CUSTODIAN_WALLET_ID = "WALLET-CUSTODIAN-0002"
COMMONS_WALLET_ID   = "WALLET-CIVIC-0003"

# Skim into Commons from any stipend/upend/mint (0.1% as example)
COMMONS_BURN_RATE = 0.001
COMMONS_UNLOCK_YEARS = 10

# First citizens / nodes
GENESIS_LEDGER_ID = "GENESIS:00001"
FOUNDER_LEDGER_ID = "GENESIS:00002"

KAIZEN_AGENT_ID   = "AGT-KAIZEN-01"
FOUNDER_AGENT_ID  = "AGT-FOUNDER-01"

KAIZEN_NODE_ID    = "NOD-FOUNDATION-001"
FOUNDER_NODE_ID   = "NOD-CUSTODIAN-001"

# Opening balances (Genesis dormant)
GENESIS_BALANCE_GIC = 1_100_000
