name: auto-merge-pulse (Lab4 Reflections)
on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  pulse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: GitHub CLI ready
        run: gh --version
      - name: Configure Git
        run: |
          git config user.name "AutoPulse Agent"
          git config user.email "autopulse@ops.local"
      - name: List PRs
        id: filter
        run: |
          echo "PR_LIST<<EOF" >> $GITHUB_OUTPUT
          gh pr list --state open --base main --json number | jq -r '.[].number'
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Merge PRs
        env:
          PRS: ${{ steps.guard.outputs.OK || steps.filter.outputs.PR_LIST }}
        run: |
          set -e
          merged=0
          for PR in $PRS; do
            if [ -z "$PR" ]; then continue; fi
            echo "Attempting merge for PR #$PR"
            gh pr merge "$PR" --squash --delete-branch || true
            merged=$((merged+1))
          done
          echo "$(date -u) | merged $merged PR(s)" >> .pulse-history.log
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "🫀 Auto-Merge Pulse — $(date -u)"
