name: Auto-Merge to Main

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 */6 * * *'  # Every 6 hours
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git
        run: |
          git config user.name "Auto-Merge Bot"
          git config user.email "auto-merge@lab4-proof.local"

      - name: Check for changes
        id: changes
        run: |
          if git diff --quiet HEAD~1 HEAD; then
            echo "has_changes=false" >> $GITHUB_OUTPUT
          else
            echo "has_changes=true" >> $GITHUB_OUTPUT
          fi

      - name: Auto-commit if changes detected
        if: steps.changes.outputs.has_changes == 'true'
        run: |
          git add -A
          git commit -m "🤖 Auto-merge: $(date -u '+%Y-%m-%d %H:%M:%S')" || exit 0
          git push origin main

      - name: Merge open PRs
        run: |
          gh pr list --state open --base main --json number | jq -r '.[].number' | while read pr; do
            if [ ! -z "$pr" ]; then
              echo "Merging PR #$pr"
              gh pr merge "$pr" --squash --delete-branch || true
            fi
          done
