name: lab4-smoke
on: [push, pull_request]
jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - run: pip install -r requirements.txt || true
      - run: python - <<'PY'
import json, hashlib, datetime
att = {"action":"domain_created","ts":datetime.datetime.utcnow().isoformat()}
print("HASH", hashlib.sha256(json.dumps(att,sort_keys=True).encode()).hexdigest()[:16])
PY
